#!/usr/bin/env python3
"""
PAPER ANALYSIS SCRIPT: build_paper_apparatus.py
Description: Combine tables into LaTeX apparatus; generate figure captions.
Output:
  - apparatus/paper_tables.tex   — All 3 tables concatenated
  - apparatus/figure_captions.md — Markdown captions for all 4 figures
"""

import sys
from pathlib import Path

# Base directory: script location → repo root
BASE_DIR = Path(__file__).resolve().parent.parent

OUTPUT = BASE_DIR / "output"

TABLE_ORDER = ['table1.tex', 'table2.tex', 'table3.tex']

FIGURE_CAPTIONS = r"""# Figure Captions

## Figure 1: Temporal Distribution of Cyber Operations by Database
**File:** fig1.png/pdf
**Section:** §4 Data & Sources
**Description:** Stacked area chart showing monthly weighted counts of cyber operations
from CISSM (blue), CSIS (yellow), and CFR (purple) databases from February 2022 to
December 2024. CISSM dominates volume throughout the period (301 weighted incidents),
driven by OSINT capture of self-attributed hacktivist DDoS operations. CSIS shows
steadier low-volume state-attributed incidents (79, temporal filtered). CFR covers only the first year
of the conflict (26 incidents, ending December 2022).
**Data:** paper_analysis_corpus.csv, weighted by analysis_weight

## Figure 2: Actor Type Composition by Database
**File:** fig2.png/pdf
**Section:** §5b Collection-Driven Measurement (F2)
**Description:** Stacked bar chart comparing actor type distributions across the three
databases (unweighted counts). CISSM: hacktivist-majority (38.5% pro-Russian hacktivist,
28.7% Russian state). CSIS: state-majority (76.8% Russian state, 15.9% pro-Russian
hacktivist). CFR: state-dominant (84.6% Russian state, 11.5% Ukrainian state, 0%
hacktivist). N values above each bar.
**Data:** corpus_with_actor_type.csv, unweighted row counts

## Figure 3: Two-Layer Model of Cyber Operations
**File:** fig3.png/pdf
**Section:** §5c Two-Layer Model (F3), §6 Discussion
**Description:** Conceptual diagram illustrating the two-layer model of cyber operations
in the Russia-Ukraine war. The surface layer contains hacktivist DDoS and defacement
operations that are self-attributed, observable in real time, and captured by CISSM's
OSINT collection. The subsurface layer contains state APT, espionage, and sabotage
operations that are anonymized, covert, and captured by curated databases (CSIS, CFR).
Each database captures a different slice of the phenomenon, producing the observed
cross-source divergence.

## Appendix Figure A1: Data Pipeline Sankey
**File:** figA1.png
**Section:** Appendix
**Description:** Sankey diagram showing the end-to-end data pipeline from raw
extraction (18,995 records) through deduplication, NLP filtering, and enrichment
to the final analysis corpus (453 records, 3 sources). Flow widths proportional to
record counts at each stage.
"""


def main():
    print("[build_paper_apparatus] Assembling paper apparatus...")

    tables_dir = OUTPUT / "tables"
    apparatus_dir = OUTPUT / "apparatus"
    apparatus_dir.mkdir(parents=True, exist_ok=True)

    # 1. Concatenate tables
    tables_out = apparatus_dir / "paper_tables.tex"
    with open(tables_out, 'w') as out:
        out.write(r"%% Auto-generated: All 3 paper tables concatenated" + "\n")
        out.write(r"%% Generated by build_paper_apparatus.py" + "\n\n")

        for tname in TABLE_ORDER:
            tpath = tables_dir / tname
            if tpath.exists():
                content = tpath.read_text()
                out.write(content)
                out.write("\n\n")
                print(f"  Added: {tname} ({len(content.split(chr(10)))} lines)")
            else:
                print(f"  WARNING: {tname} not found, skipping")

    print(f"  Wrote: {tables_out}")

    # 2. Figure captions
    caps_out = apparatus_dir / "figure_captions.md"
    with open(caps_out, 'w') as f:
        f.write(FIGURE_CAPTIONS)
    print(f"  Wrote: {caps_out}")

    # 3. Verify all expected files exist
    expected = {
        'figures/fig1.png': 'Figure 1',
        'figures/fig1.pdf': 'Figure 1 (PDF)',
        'figures/fig2.png': 'Figure 2',
        'figures/fig2.pdf': 'Figure 2 (PDF)',
        'figures/fig3.png': 'Figure 3',
        'figures/fig3.pdf': 'Figure 3 (PDF)',
        'figures/figA1.png': 'Appendix Figure',
        'tables/table1.tex': 'Table 1',
        'tables/table2.tex': 'Table 2',
        'tables/table3.tex': 'Table 3',
        'apparatus/paper_tables.tex': 'Combined tables',
        'apparatus/figure_captions.md': 'Figure captions',
    }

    print(f"\n  Verification:")
    for rel_path, label in expected.items():
        full = OUTPUT / rel_path
        exists = full.exists()
        status = 'OK' if exists else 'MISSING'
        print(f"    [{status}] {label}: {rel_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
